### ISSUE TITLE
Promote OP viem and make it more discoverable

### ISSUE THREAD

**Issue by roninjin10** [base-org/op-viem#160]
Now that OP viem is stabileish we should start driving more users to it

## Tasks

- [ ] Fork OP viem to OP repo
- [ ] Add documentation to the sdk calling out op-viem as the preferred option
- [ ] Checkin with docs team to see if there is anywhere else we can link to (this might require syncing between OP and base docs teams)
- [ ] Promote it on OP radio?
- [ ] Promote it with a dev blog post?
- [ ] Promote it with a tweet?

**Comment by therealharpaljadeja** [comment]
Is `op-viem` still going to be maintained?

The [examples](https://www.opviem.sh/docs/examples.html) in the docs seem outdated...

I want to use `op-viem` for Celo's L2 testnet bridging examples.

**Comment by roninjin10** [comment]
op-viem got updated to viem. So now you can use op-viem without needing a seperate library

Check out the docs here: https://viem.sh/op-stack
